apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: opa-policy-pipeline
  namespace: opa-demo
spec:
  resources:
    - name: source-repo
      type: git
    - name: event-to-sink
      type: cloudEvent
  tasks:
    - name: opa-policy-generate
      taskRef:
        name: opa-policy-generate
      resources:
        inputs:
          - name: workspace
            resource: source-repo
        outputs:
          - name: event-to-sink
            resource: event-to-sink
          - name: workspace
            resource: source-repo
    - name: opa-policy-unit-tests
      runAfter:
      - opa-policy-generate
      taskRef:
        name: opa-policy-unit-tests
      resources:
        inputs:
          - name: workspace
            resource: source-repo
            from: [opa-policy-generate]
        outputs:
          - name: event-to-sink
            resource: event-to-sink
    # - name: opa-policy-integration-tests
    #   runAfter:
    #   - opa-policy-unit-tests
    #   taskRef:
    #     name: opa-policy-integration-tests
    #   resources:
    #     inputs:
    #       - name: workspace
    #         resource: source-repo
    #     outputs:
    #       - name: event-to-sink
    #         resource: event-to-sink
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: opa-policy-generate
  namespace: opa-demo
spec:
  inputs:
    resources:
      - name: workspace
        type: git
  outputs:
    resources:
    - name: event-to-sink
      type: cloudEvent
    - name: workspace
      type: git
  steps:
    - name: generate-policy
      image: castlemilk/jinja2
      command: ['/bin/bash']
      args:
        - '-c'
        - |
          echo $(inputs.resources.workspace.revision)
          ls -la workspace/
          ls -la /workspace
          echo $PWD
          cd workspace/examples/test-admission-controller 
          make generate.policies CLUSTER=ci KUBE_DIR=/workspace/output/workspace
    - name: generate-manifests
      image: castlemilk/kustomize
      command: ['/bin/bash']
      args:
        - '-c'
        - |
          cd workspace/examples/test-admission-controller 
          make generate.manifests CLUSTER=ci KUBE_DIR=/workspace/output/workspace
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: opa-policy-unit-tests
  namespace: opa-demo
spec:
  inputs:
    resources:
      - name: workspace
        type: git
        targetPath: generated
  outputs:
    resources:
    - name: event-to-sink
      type: cloudEvent
  steps:
    - name: test
      image: castlemilk/opa
      args:
        - test
        - /workspace/generated/policies
        - '-v'
        - '-l'
        - '--explain'
        - 'full'
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: opa-policy-integration-tests
  namespace: opa-demo
spec:
  inputs:
    resources:
      - name: workspace
        type: git
  outputs:
    resources:
    - name: event-to-sink
      type: cloudEvent
  steps:
    - name: start-cluster
      image: castlemilk/kind
      command: ['/bin/bash']
      args:
      - '-c'
      - |
        kind create cluster
        kind load docker-image openpolicyagent/opa:0.13.4
        kind load docker-image openpolicyagent/kube-mgmt:0.9
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
    - name: anchorctl-integration-test
      image: castlemilk/kind
      command: ['kubectl']
      args:
        - 'get'
        - 'nodes'
    - name: delete-cluster
      image: castlemilk/kind
      args:
        - 'delete'
        - 'cluster'
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
  sidecars:
    - image: docker:18.05-dind
      name: server
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory