apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: opa-policy-pipeline
  namespace: opa-demo
spec:
  resources:
    - name: source-repo
      type: git
    - name: event-to-sink
      type: cloudEvent
  tasks:
    - name: opa-policy-generate
      taskRef:
        name: opa-policy-generate
      resources:
        inputs:
          - name: source-repo
            resource: source-repo
        outputs:
          - name: event-to-sink
            resource: event-to-sink
    - name: opa-policy-unit-tests
      runAfter:
      - opa-policy-generate
      taskRef:
        name: opa-policy-unit-tests
      resources:
        inputs:
          - name: source-repo
            resource: source-repo
        outputs:
          - name: event-to-sink
            resource: event-to-sink
    - name: opa-policy-integration-tests
      runAfter:
      - opa-policy-unit-tests
      taskRef:
        name: opa-policy-integration-tests
      resources:
        inputs:
          - name: source-repo
            resource: source-repo
        outputs:
          - name: event-to-sink
            resource: event-to-sink
---
  apiVersion: tekton.dev/v1alpha1
  kind: Task
  metadata:
    name: opa-policy-generate
    namespace: opa-demo
  spec:
    inputs:
      resources:
        - name: source-repo
          type: git
    outputs:
      resources:
      - name: event-to-sink
        type: cloudEvent
    steps:
      - name: generate-policy
        image: castlemilk/jinja2
        command: ['/bin/bash']
        args:
          - '-c'
          - |
            ls -la source-repo/
            cd source-repo/examples/test-admission-controller
            make generate.policies CLUSTER=ci
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: opa-policy-unit-tests
  namespace: opa-demo
spec:
  inputs:
    resources:
      - name: source-repo
        type: git
  outputs:
    resources:
    - name: event-to-sink
      type: cloudEvent
  steps:
    - name: test
      image: ubuntu
      command: ['/bin/bash']
      args:
        - '-c'
        - 'echo $(inputs.resources.source-repo.revision)'
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: opa-policy-integration-tests
  namespace: opa-demo
spec:
  inputs:
    resources:
      - name: source-repo
        type: git
  outputs:
    resources:
    - name: event-to-sink
      type: cloudEvent
  steps:
    - name: start-cluster
      image: castlemilk/kind
      args:
        - 'create'
        - 'cluster'
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
    - name: anchorctl-integration-test
      image: castlemilk/kind
      command: ['kubectl']
      args:
        - 'get'
        - 'nodes'
    - name: delete-cluster
      image: castlemilk/kind
      args:
        - 'delete'
        - 'cluster'
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
  sidecars:
    - image: docker:18.05-dind
      name: server
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory