apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- files:
  - ./policies/mutate-affinity-main.rego
  name: mutate-affinity-main
- files:
  - ./policies/common-main.rego
  name: common-main
- files:
  - ./policies/mutate-label-main.rego
  name: mutate-label-main
- files:
  - ./policies/lb-services-main.rego
  name: lb-services-main
namespace: opa
commonLabels:
  openpolicyagent.org/policy: rego
generatorOptions:
  disableNameSuffixHash: true
